name: Publish Production

on:
  pull_request:
    types: ['opened', 'edited']
    branches:
      - develop
env:
  NODE_VERSION: '20.13.1'
jobs:
  build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish NPT
        if: contains(github.pull_request.labels.*.name, 'npt')
        run: npm run build:nonprod_npt

      - name: Publish JPMC
        if: contains(github.pull_request.labels.*.name, 'jpmc')
        run: npm run build:nonprod_jpmc

      - name: Publish JPMS
        if: contains(github.pull_request.labels.*.name, 'jpms')
        run: npm run build:nonprod_jpms

      - name: Publish JPMDAF
        if: contains(github.pull_request.labels.*.name, 'jpmdaf')
        run: npm run build:nonprod_jpmdaf

      - name: Publish UBS
        if: contains(github.pull_request.labels.*.name, 'ubs')
        run: npm run build:nonprod_ubs

      - name: Publish NPTUK
        if: contains(github.pull_request.labels.*.name, 'nptuk')
        run: npm run build:nonprod_nptuk

      - name: Publish WELLS
        if: contains(github.pull_request.labels.*.name, 'wells')
        run: npm run build:nonprod_wells

      - name: Publish AB
        if: contains(github.pull_request.labels.*.name, 'ab')
        run: npm run build:nonprod_ab

      - name: Publish NPTUKUSD
        if: contains(github.pull_request.labels.*.name, 'nptukusd')
        run: npm run build:nonprod_nptukusd

      - name: Publish BMO
        if: contains(github.pull_request.labels.*.name, 'bmo')
        run: npm run build:nonprod_bmo

      - name: Create ZIP Artifacts
        run: |
          cd ${{ github.workspace }}/dist
          for folder in *; do
            zip -r $folder.zip $folder
            echo "Created zip for $folder"
            mv $folder.zip ${{ github.workspace }}/$folder.zip
          done
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: client-artifacts
          path: ${{ github.workspace }}/*.zip
